name: Update

# Controls when the workflow will run
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build
        shell: powershell
        run: |
          ls
          ls ..
          ls ./PowerEditor/visual.net
          cat ./PowerEditor/visual.net/notepadPlus.sln
          msbuild ./PowerEditor/visual.net/notepadPlus.sln -p:Configuration=Release
